# Generated by Django 2.2.2 on 2019-08-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190827_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
